# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        # ports:
        #     - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - traefik
        depends_on:
            - mariadb
        labels:
            # enable traefik and tls using letsencrypt
            traefik.enable: "true"
            traefik.http.routers.app.tls: "true"
            traefik.http.routers.app.tls.certresolver: letsencrypt
            # serve it on https://app.your-domain.com
            traefik.http.routers.app.rule: Host(`vtms.online`)

    mariadb:
        image: 'mariadb:10'
        # ports:
        #     - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmariadb:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            DEBUG: '1'
            METRICS_SERVER_PORT: '9601'
        ports:
            - '${SOKETI_PORT:-6001}:6001'
            - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
        networks:
            - sail
    nodejs:
        image: 'node:16-alpine'
        user: 'node'
        environment:
            - NODE_ENV=production
        volumes:
            - './mqtt_http_bridge:/home/node/mqtt_http_bridge'
        working_dir: '/home/node/mqtt_http_bridge'
        command: 'node index.js'
        networks:
            - sail
    mosquitto:
        image: 'eclipse-mosquitto:latest'
        volumes:
          - './mosquitto.conf:/mosquitto/config/mosquitto.conf'
        ports:
          - 1883:1883
        networks:
            - sail
    traefik:
        container_name: traefik
        image: traefik
        restart: always
        stdin_open: true
        tty: true
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik.yml:/etc/traefik/traefik.yml
        - ./acme:/etc/traefik/acme
        ports:
        - "80:80"
        - "443:443"
networks:
    sail:
        driver: bridge
    traefik:
        external:
            name: traefik
volumes:
    sailmariadb:
        driver: local
    sailredis:
        driver: local
