entryPoints:
  # http redirect to https
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  # https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
# letsencrypt TLS
certificatesResolvers:
  letsencrypt:
    acme:
      email: yasirsoleh@gmail.com
      storage: /etc/traefik/acme/acme.json
      tlsChallenge: {}
      httpChallenge:
        entryPoint: web
# listen docker
providers:
  docker:
    exposedByDefault: false
    network: traefik